# Generated by Django 5.2.8 on 2025-11-22 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_consumersupplierlink_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumersupplierlink",
            name="assigned_sales_rep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_consumers",
                to="accounts.supplierstaff",
            ),
        ),
    ]
