# Generated by Django 5.2.8 on 2025-11-22 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_enhance_complaints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints_status_56fdf2_idx',
            old_name='complaints_status_esc_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints_supplie_75af1c_idx',
            old_name='complaints_supp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints_consume_6ecb1c_idx',
            old_name='complaints_cons_created_idx',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Currently assigned staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
    ]
