# Generated by Django 5.2.8 on 2025-11-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_escalation_level'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__supplie_4669eb_idx',
            old_name='complaints_c_supplie_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__consume_ed4cf0_idx',
            old_name='complaints_c_consume_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='complaints__escalat_73fb7c_idx',
            old_name='complaints_c_escalat_idx',
        ),
    ]
