# Generated by Django 5.2.8 on 2025-11-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_rename_complaints_c_supplie_idx_complaints__supplie_4669eb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintescalation',
            name='from_level',
            field=models.CharField(choices=[('sales', 'Sales Representative'), ('manager', 'Manager'), ('owner', 'Owner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintescalation',
            name='to_level',
            field=models.CharField(choices=[('sales', 'Sales Representative'), ('manager', 'Manager'), ('owner', 'Owner')], max_length=20),
        ),
    ]
